trigger:
  - master

variables:
  BuildConfiguration: 'Release'

jobs:
  - job: Build
    pool: Hosted Windows 2019 with VS2019
    steps:
    - template: build-steps.yml
      parameters:
        BuildConfiguration: '$(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'publish function'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/*/Core.FunctionApp.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory) --no-build'

    - task: DotNetCoreCLI@2
      displayName: 'publish webapp'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/*/Core.WebApp.Server.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory) --no-build'

    - task: CopyFiles@2
      displayName: 'Copy infra files to: $(build.artifactstagingdirectory)/infra'
      inputs:
        SourceFolder: infra
        TargetFolder: '$(build.artifactstagingdirectory)/infra'                  

    - task: PublishBuildArtifacts@1
      displayName: 'publish artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'

